// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/handler/user/reqs/models.proto

// 生成的程式在 Golang 中將會屬於 `reqs` 套件。

package reqs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Member 。
type ModifyUser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyUser) Reset()         { *m = ModifyUser{} }
func (m *ModifyUser) String() string { return proto.CompactTextString(m) }
func (*ModifyUser) ProtoMessage()    {}
func (*ModifyUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_5bd1064b07ac30e2, []int{0}
}

func (m *ModifyUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUser.Unmarshal(m, b)
}
func (m *ModifyUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUser.Marshal(b, m, deterministic)
}
func (m *ModifyUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUser.Merge(m, src)
}
func (m *ModifyUser) XXX_Size() int {
	return xxx_messageInfo_ModifyUser.Size(m)
}
func (m *ModifyUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUser.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUser proto.InternalMessageInfo

func (m *ModifyUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModifyUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*ModifyUser)(nil), "reqs.ModifyUser")
}

func init() { proto.RegisterFile("src/handler/user/reqs/models.proto", fileDescriptor_5bd1064b07ac30e2) }

var fileDescriptor_5bd1064b07ac30e2 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2a, 0x2e, 0x4a, 0xd6,
	0xcf, 0x48, 0xcc, 0x4b, 0xc9, 0x49, 0x2d, 0xd2, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x2f, 0x4a, 0x2d,
	0x2c, 0xd6, 0xcf, 0xcd, 0x4f, 0x49, 0xcd, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x01, 0x09, 0x29, 0xd9, 0x70, 0x71, 0xf9, 0xe6, 0xa7, 0x64, 0xa6, 0x55, 0x86, 0x16, 0xa7, 0x16,
	0x09, 0x09, 0x71, 0xb1, 0xf8, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81,
	0xd9, 0x42, 0x52, 0x5c, 0x1c, 0x01, 0x89, 0xc5, 0xc5, 0xe5, 0xf9, 0x45, 0x29, 0x12, 0x4c, 0x60,
	0x71, 0x38, 0x3f, 0x89, 0x0d, 0x6c, 0x94, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x89, 0x09, 0x51,
	0x32, 0x70, 0x00, 0x00, 0x00,
}
