// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/database/models/menu.proto

// 生成的程式在 Golang 中將會屬於 `models` 套件。

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Shop 。
type Shop struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shop) Reset()         { *m = Shop{} }
func (m *Shop) String() string { return proto.CompactTextString(m) }
func (*Shop) ProtoMessage()    {}
func (*Shop) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{0}
}

func (m *Shop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shop.Unmarshal(m, b)
}
func (m *Shop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shop.Marshal(b, m, deterministic)
}
func (m *Shop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shop.Merge(m, src)
}
func (m *Shop) XXX_Size() int {
	return xxx_messageInfo_Shop.Size(m)
}
func (m *Shop) XXX_DiscardUnknown() {
	xxx_messageInfo_Shop.DiscardUnknown(m)
}

var xxx_messageInfo_Shop proto.InternalMessageInfo

func (m *Shop) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Shop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Item 。
type Item struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Shop_ID              int32    `protobuf:"varint,3,opt,name=Shop_ID,json=ShopID,proto3" json:"Shop_ID,omitempty"`
	Price                int32    `protobuf:"varint,4,opt,name=Price,proto3" json:"Price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{1}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetShop_ID() int32 {
	if m != nil {
		return m.Shop_ID
	}
	return 0
}

func (m *Item) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

// ItemOption 。
type ItemOption struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Item_ID              int32    `protobuf:"varint,2,opt,name=Item_ID,json=ItemID,proto3" json:"Item_ID,omitempty"`
	Option_ID            int32    `protobuf:"varint,3,opt,name=Option_ID,json=OptionID,proto3" json:"Option_ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemOption) Reset()         { *m = ItemOption{} }
func (m *ItemOption) String() string { return proto.CompactTextString(m) }
func (*ItemOption) ProtoMessage()    {}
func (*ItemOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{2}
}

func (m *ItemOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemOption.Unmarshal(m, b)
}
func (m *ItemOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemOption.Marshal(b, m, deterministic)
}
func (m *ItemOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemOption.Merge(m, src)
}
func (m *ItemOption) XXX_Size() int {
	return xxx_messageInfo_ItemOption.Size(m)
}
func (m *ItemOption) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemOption.DiscardUnknown(m)
}

var xxx_messageInfo_ItemOption proto.InternalMessageInfo

func (m *ItemOption) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ItemOption) GetItem_ID() int32 {
	if m != nil {
		return m.Item_ID
	}
	return 0
}

func (m *ItemOption) GetOption_ID() int32 {
	if m != nil {
		return m.Option_ID
	}
	return 0
}

// Option 。
type Option struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Is_Optional          bool     `protobuf:"varint,2,opt,name=Is_Optional,json=IsOptional,proto3" json:"Is_Optional,omitempty"`
	Select_Num           int32    `protobuf:"varint,3,opt,name=Select_Num,json=SelectNum,proto3" json:"Select_Num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Option) Reset()         { *m = Option{} }
func (m *Option) String() string { return proto.CompactTextString(m) }
func (*Option) ProtoMessage()    {}
func (*Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{3}
}

func (m *Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option.Unmarshal(m, b)
}
func (m *Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option.Marshal(b, m, deterministic)
}
func (m *Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option.Merge(m, src)
}
func (m *Option) XXX_Size() int {
	return xxx_messageInfo_Option.Size(m)
}
func (m *Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Option proto.InternalMessageInfo

func (m *Option) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Option) GetIs_Optional() bool {
	if m != nil {
		return m.Is_Optional
	}
	return false
}

func (m *Option) GetSelect_Num() int32 {
	if m != nil {
		return m.Select_Num
	}
	return 0
}

// OptionSelection 。
type OptionSelection struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Option_ID            int32    `protobuf:"varint,2,opt,name=Option_ID,json=OptionID,proto3" json:"Option_ID,omitempty"`
	Selection_ID         int32    `protobuf:"varint,3,opt,name=Selection_ID,json=SelectionID,proto3" json:"Selection_ID,omitempty"`
	Price                int32    `protobuf:"varint,4,opt,name=Price,proto3" json:"Price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptionSelection) Reset()         { *m = OptionSelection{} }
func (m *OptionSelection) String() string { return proto.CompactTextString(m) }
func (*OptionSelection) ProtoMessage()    {}
func (*OptionSelection) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{4}
}

func (m *OptionSelection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptionSelection.Unmarshal(m, b)
}
func (m *OptionSelection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptionSelection.Marshal(b, m, deterministic)
}
func (m *OptionSelection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionSelection.Merge(m, src)
}
func (m *OptionSelection) XXX_Size() int {
	return xxx_messageInfo_OptionSelection.Size(m)
}
func (m *OptionSelection) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionSelection.DiscardUnknown(m)
}

var xxx_messageInfo_OptionSelection proto.InternalMessageInfo

func (m *OptionSelection) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *OptionSelection) GetOption_ID() int32 {
	if m != nil {
		return m.Option_ID
	}
	return 0
}

func (m *OptionSelection) GetSelection_ID() int32 {
	if m != nil {
		return m.Selection_ID
	}
	return 0
}

func (m *OptionSelection) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

// selection
type Selection struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Selection) Reset()         { *m = Selection{} }
func (m *Selection) String() string { return proto.CompactTextString(m) }
func (*Selection) ProtoMessage()    {}
func (*Selection) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{5}
}

func (m *Selection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Selection.Unmarshal(m, b)
}
func (m *Selection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Selection.Marshal(b, m, deterministic)
}
func (m *Selection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Selection.Merge(m, src)
}
func (m *Selection) XXX_Size() int {
	return xxx_messageInfo_Selection.Size(m)
}
func (m *Selection) XXX_DiscardUnknown() {
	xxx_messageInfo_Selection.DiscardUnknown(m)
}

var xxx_messageInfo_Selection proto.InternalMessageInfo

func (m *Selection) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Selection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Shop)(nil), "models.Shop")
	proto.RegisterType((*Item)(nil), "models.Item")
	proto.RegisterType((*ItemOption)(nil), "models.ItemOption")
	proto.RegisterType((*Option)(nil), "models.Option")
	proto.RegisterType((*OptionSelection)(nil), "models.OptionSelection")
	proto.RegisterType((*Selection)(nil), "models.Selection")
}

func init() { proto.RegisterFile("src/database/models/menu.proto", fileDescriptor_6cc3f7e2ebb06a21) }

var fileDescriptor_6cc3f7e2ebb06a21 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0xed, 0xba, 0xf5, 0x3f, 0x51, 0x08, 0xc2, 0x0a, 0xa2, 0xce, 0x9c, 0x86, 0x07,
	0x7b, 0xf0, 0x2b, 0xe4, 0x92, 0x4b, 0x95, 0xee, 0xa2, 0xa7, 0x92, 0x75, 0x01, 0x07, 0xcd, 0x52,
	0x9a, 0x14, 0xbf, 0xbe, 0x24, 0xd1, 0x8d, 0xe1, 0x0a, 0xde, 0xfa, 0x7e, 0x79, 0xef, 0xf7, 0x7f,
	0xf4, 0xe1, 0xde, 0xf4, 0x4d, 0xb1, 0x15, 0x56, 0x6c, 0x84, 0x91, 0x85, 0xd2, 0x5b, 0xd9, 0x9a,
	0x42, 0xc9, 0xfd, 0xf0, 0xdc, 0xf5, 0xda, 0x6a, 0x92, 0x06, 0x44, 0x9f, 0x90, 0xac, 0x3f, 0x75,
	0x47, 0xae, 0x10, 0x73, 0x96, 0x47, 0xcb, 0x68, 0x35, 0xa9, 0x62, 0xce, 0x08, 0x41, 0x52, 0x0a,
	0x25, 0xf3, 0x78, 0x19, 0xad, 0xb2, 0xca, 0x7f, 0xd3, 0x0f, 0x24, 0xdc, 0x4a, 0xf5, 0x9f, 0x5e,
	0xb2, 0xc0, 0xd4, 0x79, 0x6b, 0xce, 0xf2, 0x0b, 0xdf, 0x98, 0xba, 0x92, 0x33, 0x72, 0x83, 0xc9,
	0x5b, 0xbf, 0x6b, 0x64, 0x9e, 0x78, 0x1c, 0x0a, 0x5a, 0x01, 0x4e, 0xfd, 0xda, 0xd9, 0x9d, 0xde,
	0xff, 0x09, 0x58, 0x60, 0xea, 0x5e, 0x9d, 0x2c, 0x0e, 0x32, 0x57, 0x72, 0x46, 0x6e, 0x91, 0x85,
	0x91, 0x63, 0xce, 0x2c, 0x00, 0xce, 0xe8, 0x3b, 0xd2, 0x11, 0xdf, 0x03, 0xe6, 0xdc, 0xd4, 0xe1,
	0x51, 0xb4, 0xde, 0x39, 0xab, 0xc0, 0xcd, 0x2f, 0x21, 0x77, 0xc0, 0x5a, 0xb6, 0xb2, 0xb1, 0x75,
	0x39, 0xa8, 0x1f, 0x71, 0x16, 0x48, 0x39, 0x28, 0xfa, 0x85, 0xeb, 0xd0, 0x1a, 0xd0, 0xb9, 0x88,
	0x93, 0xcd, 0xe2, 0xd3, 0xcd, 0xc8, 0x23, 0x2e, 0x0f, 0x93, 0xc7, 0xcd, 0xe7, 0x07, 0x36, 0xfa,
	0x9b, 0x0a, 0x64, 0xe3, 0x91, 0x67, 0xce, 0xb0, 0x49, 0xfd, 0xb5, 0x5f, 0xbe, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xd6, 0xf1, 0xcb, 0xfa, 0x0f, 0x02, 0x00, 0x00,
}
