// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/database/models/menu.proto

// 生成的程式在 Golang 中將會屬於 `models` 套件。

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Shop 。
type Shop struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shop) Reset()         { *m = Shop{} }
func (m *Shop) String() string { return proto.CompactTextString(m) }
func (*Shop) ProtoMessage()    {}
func (*Shop) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{0}
}

func (m *Shop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shop.Unmarshal(m, b)
}
func (m *Shop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shop.Marshal(b, m, deterministic)
}
func (m *Shop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shop.Merge(m, src)
}
func (m *Shop) XXX_Size() int {
	return xxx_messageInfo_Shop.Size(m)
}
func (m *Shop) XXX_DiscardUnknown() {
	xxx_messageInfo_Shop.DiscardUnknown(m)
}

var xxx_messageInfo_Shop proto.InternalMessageInfo

func (m *Shop) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Shop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ShopItem struct {
	ShopID               int32    `protobuf:"varint,1,opt,name=ShopID,proto3" json:"ShopID,omitempty"`
	MenuItemID           int32    `protobuf:"varint,2,opt,name=MenuItemID,proto3" json:"MenuItemID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopItem) Reset()         { *m = ShopItem{} }
func (m *ShopItem) String() string { return proto.CompactTextString(m) }
func (*ShopItem) ProtoMessage()    {}
func (*ShopItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{1}
}

func (m *ShopItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopItem.Unmarshal(m, b)
}
func (m *ShopItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopItem.Marshal(b, m, deterministic)
}
func (m *ShopItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopItem.Merge(m, src)
}
func (m *ShopItem) XXX_Size() int {
	return xxx_messageInfo_ShopItem.Size(m)
}
func (m *ShopItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopItem.DiscardUnknown(m)
}

var xxx_messageInfo_ShopItem proto.InternalMessageInfo

func (m *ShopItem) GetShopID() int32 {
	if m != nil {
		return m.ShopID
	}
	return 0
}

func (m *ShopItem) GetMenuItemID() int32 {
	if m != nil {
		return m.MenuItemID
	}
	return 0
}

// Item 。
type Item struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{2}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Size 。
type Size struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{3}
}

func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (m *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(m, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

func (m *Size) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Size) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// ItemSize 。
type ItemSize struct {
	ItemID               int32    `protobuf:"varint,1,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	SizeID               int32    `protobuf:"varint,2,opt,name=SizeID,proto3" json:"SizeID,omitempty"`
	Prices               int32    `protobuf:"varint,3,opt,name=Prices,proto3" json:"Prices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemSize) Reset()         { *m = ItemSize{} }
func (m *ItemSize) String() string { return proto.CompactTextString(m) }
func (*ItemSize) ProtoMessage()    {}
func (*ItemSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{4}
}

func (m *ItemSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemSize.Unmarshal(m, b)
}
func (m *ItemSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemSize.Marshal(b, m, deterministic)
}
func (m *ItemSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemSize.Merge(m, src)
}
func (m *ItemSize) XXX_Size() int {
	return xxx_messageInfo_ItemSize.Size(m)
}
func (m *ItemSize) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemSize.DiscardUnknown(m)
}

var xxx_messageInfo_ItemSize proto.InternalMessageInfo

func (m *ItemSize) GetItemID() int32 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *ItemSize) GetSizeID() int32 {
	if m != nil {
		return m.SizeID
	}
	return 0
}

func (m *ItemSize) GetPrices() int32 {
	if m != nil {
		return m.Prices
	}
	return 0
}

// Kind 。
type Kind struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Kind) Reset()         { *m = Kind{} }
func (m *Kind) String() string { return proto.CompactTextString(m) }
func (*Kind) ProtoMessage()    {}
func (*Kind) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{5}
}

func (m *Kind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kind.Unmarshal(m, b)
}
func (m *Kind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kind.Marshal(b, m, deterministic)
}
func (m *Kind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kind.Merge(m, src)
}
func (m *Kind) XXX_Size() int {
	return xxx_messageInfo_Kind.Size(m)
}
func (m *Kind) XXX_DiscardUnknown() {
	xxx_messageInfo_Kind.DiscardUnknown(m)
}

var xxx_messageInfo_Kind proto.InternalMessageInfo

func (m *Kind) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Kind) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// ItemKind 。
type ItemKind struct {
	ItemID               int32    `protobuf:"varint,1,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	KindID               int32    `protobuf:"varint,2,opt,name=KindID,proto3" json:"KindID,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemKind) Reset()         { *m = ItemKind{} }
func (m *ItemKind) String() string { return proto.CompactTextString(m) }
func (*ItemKind) ProtoMessage()    {}
func (*ItemKind) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{6}
}

func (m *ItemKind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemKind.Unmarshal(m, b)
}
func (m *ItemKind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemKind.Marshal(b, m, deterministic)
}
func (m *ItemKind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemKind.Merge(m, src)
}
func (m *ItemKind) XXX_Size() int {
	return xxx_messageInfo_ItemKind.Size(m)
}
func (m *ItemKind) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemKind.DiscardUnknown(m)
}

var xxx_messageInfo_ItemKind proto.InternalMessageInfo

func (m *ItemKind) GetItemID() int32 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *ItemKind) GetKindID() int32 {
	if m != nil {
		return m.KindID
	}
	return 0
}

func (m *ItemKind) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type SizePrice struct {
	Size                 string   `protobuf:"bytes,1,opt,name=Size,proto3" json:"Size,omitempty"`
	Price                int32    `protobuf:"varint,2,opt,name=Price,proto3" json:"Price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SizePrice) Reset()         { *m = SizePrice{} }
func (m *SizePrice) String() string { return proto.CompactTextString(m) }
func (*SizePrice) ProtoMessage()    {}
func (*SizePrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{7}
}

func (m *SizePrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizePrice.Unmarshal(m, b)
}
func (m *SizePrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizePrice.Marshal(b, m, deterministic)
}
func (m *SizePrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizePrice.Merge(m, src)
}
func (m *SizePrice) XXX_Size() int {
	return xxx_messageInfo_SizePrice.Size(m)
}
func (m *SizePrice) XXX_DiscardUnknown() {
	xxx_messageInfo_SizePrice.DiscardUnknown(m)
}

var xxx_messageInfo_SizePrice proto.InternalMessageInfo

func (m *SizePrice) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *SizePrice) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type KindPrice struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Price                int32    `protobuf:"varint,2,opt,name=Price,proto3" json:"Price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KindPrice) Reset()         { *m = KindPrice{} }
func (m *KindPrice) String() string { return proto.CompactTextString(m) }
func (*KindPrice) ProtoMessage()    {}
func (*KindPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{8}
}

func (m *KindPrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KindPrice.Unmarshal(m, b)
}
func (m *KindPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KindPrice.Marshal(b, m, deterministic)
}
func (m *KindPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KindPrice.Merge(m, src)
}
func (m *KindPrice) XXX_Size() int {
	return xxx_messageInfo_KindPrice.Size(m)
}
func (m *KindPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_KindPrice.DiscardUnknown(m)
}

var xxx_messageInfo_KindPrice proto.InternalMessageInfo

func (m *KindPrice) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *KindPrice) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

// MenuItem 。
type MenuItem struct {
	Item                 *Item        `protobuf:"bytes,1,opt,name=Item,proto3" json:"Item,omitempty"`
	SizePrice            []*SizePrice `protobuf:"bytes,2,rep,name=SizePrice,proto3" json:"SizePrice,omitempty"`
	KindPrice            []*KindPrice `protobuf:"bytes,3,rep,name=KindPrice,proto3" json:"KindPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MenuItem) Reset()         { *m = MenuItem{} }
func (m *MenuItem) String() string { return proto.CompactTextString(m) }
func (*MenuItem) ProtoMessage()    {}
func (*MenuItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6cc3f7e2ebb06a21, []int{9}
}

func (m *MenuItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuItem.Unmarshal(m, b)
}
func (m *MenuItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuItem.Marshal(b, m, deterministic)
}
func (m *MenuItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuItem.Merge(m, src)
}
func (m *MenuItem) XXX_Size() int {
	return xxx_messageInfo_MenuItem.Size(m)
}
func (m *MenuItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuItem.DiscardUnknown(m)
}

var xxx_messageInfo_MenuItem proto.InternalMessageInfo

func (m *MenuItem) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *MenuItem) GetSizePrice() []*SizePrice {
	if m != nil {
		return m.SizePrice
	}
	return nil
}

func (m *MenuItem) GetKindPrice() []*KindPrice {
	if m != nil {
		return m.KindPrice
	}
	return nil
}

func init() {
	proto.RegisterType((*Shop)(nil), "models.Shop")
	proto.RegisterType((*ShopItem)(nil), "models.ShopItem")
	proto.RegisterType((*Item)(nil), "models.Item")
	proto.RegisterType((*Size)(nil), "models.Size")
	proto.RegisterType((*ItemSize)(nil), "models.ItemSize")
	proto.RegisterType((*Kind)(nil), "models.Kind")
	proto.RegisterType((*ItemKind)(nil), "models.ItemKind")
	proto.RegisterType((*SizePrice)(nil), "models.SizePrice")
	proto.RegisterType((*KindPrice)(nil), "models.KindPrice")
	proto.RegisterType((*MenuItem)(nil), "models.MenuItem")
}

func init() { proto.RegisterFile("src/database/models/menu.proto", fileDescriptor_6cc3f7e2ebb06a21) }

var fileDescriptor_6cc3f7e2ebb06a21 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x6a, 0x83, 0x40,
	0x10, 0x86, 0x51, 0xa3, 0xe8, 0xa4, 0x14, 0xba, 0x94, 0xe0, 0x29, 0x88, 0x27, 0xe9, 0x41, 0x21,
	0xa5, 0x2f, 0x50, 0xbc, 0x48, 0x69, 0x09, 0xdb, 0x27, 0x30, 0x71, 0xa1, 0x42, 0xd5, 0xa0, 0xe6,
	0x92, 0x87, 0xe8, 0x33, 0x97, 0x99, 0x59, 0x37, 0xb6, 0x94, 0xe2, 0x6d, 0xff, 0xd9, 0xff, 0xdf,
	0xef, 0xd7, 0x5d, 0xd8, 0x0e, 0xfd, 0x31, 0xab, 0xca, 0xb1, 0x3c, 0x94, 0x83, 0xca, 0x9a, 0xae,
	0x52, 0x9f, 0x43, 0xd6, 0xa8, 0xf6, 0x9c, 0x9e, 0xfa, 0x6e, 0xec, 0x84, 0xc7, 0xa3, 0xf8, 0x01,
	0x56, 0xef, 0x1f, 0xdd, 0x49, 0xdc, 0x82, 0x5d, 0xe4, 0xa1, 0x15, 0x59, 0x89, 0x2b, 0xed, 0x22,
	0x17, 0x02, 0x56, 0x6f, 0x65, 0xa3, 0x42, 0x3b, 0xb2, 0x92, 0x40, 0xd2, 0x3a, 0x7e, 0x06, 0x1f,
	0xbd, 0xc5, 0xa8, 0x1a, 0xb1, 0x01, 0x8f, 0xd6, 0x53, 0x46, 0x2b, 0xb1, 0x05, 0x78, 0x55, 0xed,
	0x19, 0x3d, 0x45, 0x4e, 0x69, 0x57, 0xce, 0x26, 0xc8, 0xa3, 0xfc, 0x12, 0x1e, 0x76, 0xab, 0x2f,
	0x6a, 0x91, 0x57, 0x82, 0x8f, 0xe7, 0x92, 0x7f, 0x03, 0x9e, 0xe6, 0xeb, 0x6e, 0xac, 0xa8, 0x73,
	0x7d, 0x51, 0xa6, 0x97, 0x56, 0x38, 0xdf, 0xf7, 0xf5, 0x51, 0x0d, 0xa1, 0xc3, 0x73, 0x56, 0xc8,
	0x7f, 0xa9, 0xdb, 0x6a, 0x11, 0x7f, 0xcf, 0x7c, 0xf2, 0xff, 0xc3, 0xc7, 0xfd, 0x2b, 0x9f, 0x95,
	0xb8, 0x07, 0x97, 0x88, 0x1a, 0xcf, 0x22, 0x7e, 0x82, 0x00, 0xfb, 0x91, 0x40, 0x24, 0x0a, 0x3a,
	0x30, 0x90, 0xfc, 0x5b, 0x4c, 0xcc, 0xfe, 0x15, 0xc3, 0x63, 0x4d, 0x0c, 0xc5, 0x14, 0xa3, 0x76,
	0x7f, 0xc7, 0xbe, 0x2c, 0xf0, 0xa7, 0x6b, 0x12, 0x11, 0x5f, 0x12, 0xc5, 0xd6, 0xbb, 0x9b, 0x94,
	0xdf, 0x4a, 0x8a, 0x33, 0xc9, 0xd7, 0x97, 0xcd, 0xca, 0x85, 0x76, 0xe4, 0x24, 0xeb, 0xdd, 0xdd,
	0x64, 0x33, 0x1b, 0x72, 0xf6, 0x01, 0xd9, 0xac, 0x56, 0xe8, 0xfc, 0x0c, 0x98, 0x0d, 0x79, 0xf5,
	0x1c, 0x3c, 0x7a, 0xa7, 0x8f, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x19, 0x27, 0x39, 0xc9,
	0x02, 0x00, 0x00,
}
