// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/handler/models/resp/menu.proto

// 生成的程式在 Golang 中將會屬於 `resp` 套件。

package resp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MenuSelection struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 int32    `protobuf:"varint,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuSelection) Reset()         { *m = MenuSelection{} }
func (m *MenuSelection) String() string { return proto.CompactTextString(m) }
func (*MenuSelection) ProtoMessage()    {}
func (*MenuSelection) Descriptor() ([]byte, []int) {
	return fileDescriptor_9605b9fdee46970e, []int{0}
}

func (m *MenuSelection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuSelection.Unmarshal(m, b)
}
func (m *MenuSelection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuSelection.Marshal(b, m, deterministic)
}
func (m *MenuSelection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuSelection.Merge(m, src)
}
func (m *MenuSelection) XXX_Size() int {
	return xxx_messageInfo_MenuSelection.Size(m)
}
func (m *MenuSelection) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuSelection.DiscardUnknown(m)
}

var xxx_messageInfo_MenuSelection proto.InternalMessageInfo

func (m *MenuSelection) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MenuSelection) GetName() int32 {
	if m != nil {
		return m.Name
	}
	return 0
}

func (m *MenuSelection) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type MenuOption struct {
	ID                   int32            `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SelectNum            int32            `protobuf:"varint,2,opt,name=SelectNum,proto3" json:"SelectNum,omitempty"`
	Selection            []*MenuSelection `protobuf:"bytes,3,rep,name=Selection,proto3" json:"Selection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MenuOption) Reset()         { *m = MenuOption{} }
func (m *MenuOption) String() string { return proto.CompactTextString(m) }
func (*MenuOption) ProtoMessage()    {}
func (*MenuOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_9605b9fdee46970e, []int{1}
}

func (m *MenuOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuOption.Unmarshal(m, b)
}
func (m *MenuOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuOption.Marshal(b, m, deterministic)
}
func (m *MenuOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuOption.Merge(m, src)
}
func (m *MenuOption) XXX_Size() int {
	return xxx_messageInfo_MenuOption.Size(m)
}
func (m *MenuOption) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuOption.DiscardUnknown(m)
}

var xxx_messageInfo_MenuOption proto.InternalMessageInfo

func (m *MenuOption) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MenuOption) GetSelectNum() int32 {
	if m != nil {
		return m.SelectNum
	}
	return 0
}

func (m *MenuOption) GetSelection() []*MenuSelection {
	if m != nil {
		return m.Selection
	}
	return nil
}

type MenuItem struct {
	ID                   int32         `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Options              []*MenuOption `protobuf:"bytes,3,rep,name=Options,proto3" json:"Options,omitempty"`
	Price                int32         `protobuf:"varint,4,opt,name=Price,proto3" json:"Price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MenuItem) Reset()         { *m = MenuItem{} }
func (m *MenuItem) String() string { return proto.CompactTextString(m) }
func (*MenuItem) ProtoMessage()    {}
func (*MenuItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_9605b9fdee46970e, []int{2}
}

func (m *MenuItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuItem.Unmarshal(m, b)
}
func (m *MenuItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuItem.Marshal(b, m, deterministic)
}
func (m *MenuItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuItem.Merge(m, src)
}
func (m *MenuItem) XXX_Size() int {
	return xxx_messageInfo_MenuItem.Size(m)
}
func (m *MenuItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuItem.DiscardUnknown(m)
}

var xxx_messageInfo_MenuItem proto.InternalMessageInfo

func (m *MenuItem) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MenuItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MenuItem) GetOptions() []*MenuOption {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *MenuItem) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ShopMenu struct {
	Shop                 *Shop       `protobuf:"bytes,1,opt,name=Shop,proto3" json:"Shop,omitempty"`
	Items                []*MenuItem `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ShopMenu) Reset()         { *m = ShopMenu{} }
func (m *ShopMenu) String() string { return proto.CompactTextString(m) }
func (*ShopMenu) ProtoMessage()    {}
func (*ShopMenu) Descriptor() ([]byte, []int) {
	return fileDescriptor_9605b9fdee46970e, []int{3}
}

func (m *ShopMenu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopMenu.Unmarshal(m, b)
}
func (m *ShopMenu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopMenu.Marshal(b, m, deterministic)
}
func (m *ShopMenu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopMenu.Merge(m, src)
}
func (m *ShopMenu) XXX_Size() int {
	return xxx_messageInfo_ShopMenu.Size(m)
}
func (m *ShopMenu) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopMenu.DiscardUnknown(m)
}

var xxx_messageInfo_ShopMenu proto.InternalMessageInfo

func (m *ShopMenu) GetShop() *Shop {
	if m != nil {
		return m.Shop
	}
	return nil
}

func (m *ShopMenu) GetItems() []*MenuItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type Shop struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shop) Reset()         { *m = Shop{} }
func (m *Shop) String() string { return proto.CompactTextString(m) }
func (*Shop) ProtoMessage()    {}
func (*Shop) Descriptor() ([]byte, []int) {
	return fileDescriptor_9605b9fdee46970e, []int{4}
}

func (m *Shop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shop.Unmarshal(m, b)
}
func (m *Shop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shop.Marshal(b, m, deterministic)
}
func (m *Shop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shop.Merge(m, src)
}
func (m *Shop) XXX_Size() int {
	return xxx_messageInfo_Shop.Size(m)
}
func (m *Shop) XXX_DiscardUnknown() {
	xxx_messageInfo_Shop.DiscardUnknown(m)
}

var xxx_messageInfo_Shop proto.InternalMessageInfo

func (m *Shop) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Shop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*MenuSelection)(nil), "resp.MenuSelection")
	proto.RegisterType((*MenuOption)(nil), "resp.MenuOption")
	proto.RegisterType((*MenuItem)(nil), "resp.MenuItem")
	proto.RegisterType((*ShopMenu)(nil), "resp.ShopMenu")
	proto.RegisterType((*Shop)(nil), "resp.Shop")
}

func init() { proto.RegisterFile("src/handler/models/resp/menu.proto", fileDescriptor_9605b9fdee46970e) }

var fileDescriptor_9605b9fdee46970e = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x69, 0x9a, 0x68, 0x3b, 0xc5, 0x22, 0xab, 0x87, 0x3d, 0x88, 0x94, 0xc5, 0x43, 0xe9,
	0x21, 0xc1, 0xfa, 0x15, 0x7a, 0xc9, 0xc1, 0x5a, 0xb6, 0x9f, 0xa0, 0xa6, 0x03, 0x0d, 0x64, 0xff,
	0xb0, 0x9b, 0x7c, 0x7f, 0x99, 0xdd, 0x94, 0x55, 0x10, 0xf1, 0x36, 0x79, 0x6f, 0xf2, 0xde, 0x6f,
	0x58, 0x10, 0xde, 0x35, 0xd5, 0xe5, 0xa4, 0xcf, 0x1d, 0xba, 0x4a, 0x99, 0x33, 0x76, 0xbe, 0x72,
	0xe8, 0x6d, 0xa5, 0x50, 0x0f, 0xa5, 0x75, 0xa6, 0x37, 0x2c, 0x27, 0x41, 0xd4, 0x70, 0xf7, 0x8e,
	0x7a, 0x38, 0x62, 0x87, 0x4d, 0xdf, 0x1a, 0xcd, 0x96, 0x90, 0xd5, 0x3b, 0x3e, 0x59, 0x4d, 0xd6,
	0x85, 0xcc, 0xea, 0x1d, 0x63, 0x90, 0xef, 0x4f, 0x0a, 0x79, 0x16, 0x94, 0x30, 0xb3, 0x47, 0x28,
	0x0e, 0xae, 0x6d, 0x90, 0x4f, 0x83, 0x18, 0x3f, 0x84, 0x02, 0xa0, 0xa8, 0x0f, 0xfb, 0x6b, 0xce,
	0x13, 0xcc, 0x63, 0xc9, 0x7e, 0x50, 0x63, 0x58, 0x12, 0xd8, 0xeb, 0xd5, 0x6d, 0x8d, 0xe6, 0xd3,
	0xd5, 0x74, 0xbd, 0xd8, 0x3e, 0x94, 0x04, 0x58, 0xfe, 0xa0, 0x93, 0x69, 0x4b, 0x58, 0x98, 0x91,
	0x57, 0xf7, 0xa8, 0xfe, 0x84, 0x9e, 0x8f, 0xd0, 0x1b, 0xb8, 0x8d, 0x68, 0x7e, 0x2c, 0xb8, 0x4f,
	0x05, 0xd1, 0x90, 0xd7, 0x85, 0x74, 0x60, 0xfe, 0xfd, 0xc0, 0x03, 0xcc, 0x8e, 0x17, 0x63, 0xe9,
	0x07, 0xf6, 0x0c, 0x39, 0xcd, 0xa1, 0x73, 0xb1, 0x85, 0x18, 0x45, 0x8a, 0x0c, 0x3a, 0x7b, 0x81,
	0x82, 0xc8, 0x3c, 0xcf, 0x42, 0xd7, 0x32, 0x75, 0x91, 0x2c, 0xa3, 0x29, 0x36, 0x31, 0xe5, 0x3f,
	0xfc, 0x9f, 0x37, 0xe1, 0xd9, 0xde, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xf5, 0x49, 0x57,
	0xdc, 0x01, 0x00, 0x00,
}
