server:
  host: ""
  port: 5487

mysql_dbm:
  address: "localhost:3306"
  username: "root"
  password: "root"
  database: ""
  param: "charset=utf8mb4&parseTime=true"
mysql_member:
  address: "localhost:3306"
  username: "root"
  password: "root"
  database: "orderfood_member"
  param: "charset=utf8mb4&parseTime=true"
mysql_menu:
  address: "localhost:3306"
  username: "root"
  password: "root"
  database: "orderfood_menu"
  param: "charset=utf8mb4&parseTime=true"

redis_member:
  address: "localhost:6380"
  password: "root"
  database: "0"
redis_menu:
  address: "localhost:6380"
  password: "root"
  database: "1"

txt:
  address: "./data"
  username: ""
  password: ""
  database: "order_member"
  param: ""