server:
  host: ""
  port: 5487

mysql_dbm:
  address: "172.19.0.9:3306"
  username: "root"
  password: "root"
  database: ""
  param: "charset=utf8mb4&parseTime=true"
mysql_member:
  address: "172.19.0.9:3306"
  username: "root"
  password: "root"
  database: "orderfood_member"
  param: "charset=utf8mb4&parseTime=true"
mysql_menu:
  address: "172.19.0.9:3306"
  username: "root"
  password: "root"
  database: "orderfood_menu"
  param: "charset=utf8mb4&parseTime=true"

redis_member:
  address: "172.19.0.10:6380"
  password: "root"
  database: "0"
redis_menu:
  address: "172.19.0.10:6380"
  password: "root"
  database: "1"