server:
  host: ""
  port: 5487

mysql_dbm:
  domain: "172.19.0.9:3306"
  username: "root"
  password: "root"
  database: ""
  param: "charset=utf8mb4&parseTime=true"
mysql_member:
  domain: "172.19.0.9:3306"
  username: "root"
  password: "root"
  database: "orderfood_member"
  param: "charset=utf8mb4&parseTime=true"
mysql_menu:
  domain: "172.19.0.9:3306"
  username: "root"
  password: "root"
  database: "orderfood_menu"
  param: "charset=utf8mb4&parseTime=true"