basePath: /api/
definitions:
  models.Member:
    properties:
      ID:
        type: integer
      Password:
        type: string
      Username:
        type: string
      name:
        type: string
    type: object
  reqs.ModifyUser:
    properties:
      Name:
        type: string
      Password:
        type: string
      Username:
        type: string
    type: object
  resp.Item:
    properties:
      ID:
        type: integer
      Name:
        type: string
      Options:
        type: string
      Price:
        type: integer
    type: object
  resp.ItemOption:
    properties:
      ID:
        type: integer
      ItemID:
        type: integer
      OptionID:
        type: integer
    type: object
  resp.MenuItem:
    properties:
      Item:
        $ref: '#/definitions/resp.Item'
        type: object
      Options:
        items:
          $ref: '#/definitions/resp.MenuOption'
        type: array
    type: object
  resp.MenuOption:
    properties:
      Option:
        $ref: '#/definitions/resp.Option'
        type: object
      Selection:
        items:
          $ref: '#/definitions/resp.MenuSelection'
        type: array
    type: object
  resp.MenuSelection:
    properties:
      ID:
        type: integer
      Name:
        type: string
      Price:
        type: integer
    type: object
  resp.Option:
    properties:
      ID:
        type: integer
      SelectNum:
        type: integer
    type: object
  resp.Shop:
    properties:
      ID:
        type: integer
      Name:
        type: string
    type: object
  resp.ShopMenu:
    properties:
      Items:
        items:
          $ref: '#/definitions/resp.MenuItem'
        type: array
      Shop:
        $ref: '#/definitions/resp.Shop'
        type: object
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: 訂餐系統
  license: {}
  title: Order Food API
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 註冊
      parameters:
      - description: 稱號
        in: formData
        name: name
        required: true
        type: string
      - description: 帳號
        in: formData
        name: username
        required: true
        type: string
      - description: 密碼
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 註冊
      tags:
      - auth
  /menu:
    get:
      description: 取得菜單
      produces:
      - application/json
      responses:
        "200":
          description: 菜單
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 取得菜單
      tags:
      - shop
  /menu/item:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 新增商品
      parameters:
      - description: 商店
        in: formData
        name: shopID
        required: true
        type: integer
      - description: 商名
        in: formData
        name: name
        required: true
        type: string
      - description: 價格
        in: formData
        name: price
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 菜單
          schema:
            $ref: '#/definitions/resp.Item'
            type: object
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 新增商品
      tags:
      - menu
  /menu/item/{id}:
    delete:
      description: 刪除商品
      parameters:
      - description: 編號
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 刪除商品
      tags:
      - menu
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: 修改商品
      parameters:
      - description: 編號
        in: path
        name: id
        required: true
        type: integer
      - description: 品名
        in: formData
        name: name
        type: string
      - description: 價格
        in: formData
        name: price
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 結果
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 修改商品
      tags:
      - menu
  /menu/item/{shopID}:
    get:
      description: 取得商品
      parameters:
      - description: 商店編號
        in: path
        name: shopID
        required: true
        type: integer
      - description: 選單編號
        in: query
        name: optionID
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 菜單
          schema:
            items:
              $ref: '#/definitions/resp.Item'
            type: array
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 取得商品
      tags:
      - menu
  /menu/itemOption:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 商品加入選單
      parameters:
      - description: 商品編號
        in: formData
        name: itemID
        required: true
        type: integer
      - description: 選單編號
        in: formData
        name: optionID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 結果
          schema:
            $ref: '#/definitions/resp.ItemOption'
            type: object
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 商品加入選單
      tags:
      - menu
  /menu/itemOption/{id}:
    delete:
      description: 刪除選單的商品
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 刪除選單的商品
      tags:
      - menu
  /menu/menu/{shop}:
    get:
      description: 取得菜單
      parameters:
      - description: 商店
        in: path
        name: shop
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 菜單
          schema:
            items:
              $ref: '#/definitions/resp.ShopMenu'
            type: array
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 取得菜單
      tags:
      - menu
  /menu/option:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 新增商品選單
      parameters:
      - description: 選單選項
        in: formData
        name: selectionName
        required: true
        type: string
      - description: 必選數
        in: formData
        name: selectNum
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 商品選單
          schema:
            $ref: '#/definitions/resp.Option'
            type: object
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 新增商品選單
      tags:
      - menu
  /menu/option/{id}:
    get:
      description: 刪除商品選單
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 刪除商品選單
      tags:
      - menu
    put:
      description: 修改商品選單
      parameters:
      - description: 商品選單
        in: formData
        name: selectNum
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 修改商品選單
      tags:
      - menu
  /menu/selection:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 新增選單選項
      parameters:
      - description: 選單編號
        in: formData
        name: optionID
        required: true
        type: integer
      - description: 名稱
        in: formData
        name: name
        required: true
        type: string
      - description: 價格
        in: formData
        name: price
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 菜單
          schema:
            $ref: '#/definitions/resp.MenuSelection'
            type: object
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 新增選單選項
      tags:
      - menu
  /menu/selection/{id}:
    get:
      description: 刪除選單選項
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 刪除選單選項
      tags:
      - menu
    put:
      description: 修改選單選項
      parameters:
      - description: 名稱
        in: formData
        name: name
        type: string
      - description: 價格
        in: formData
        name: price
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 結果
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 修改選單選項
      tags:
      - menu
  /menu/shop:
    get:
      description: 取得商店
      parameters:
      - description: 編號
        in: query
        name: id
        type: string
      - description: 商名
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 菜單
          schema:
            items:
              $ref: '#/definitions/resp.Shop'
            type: array
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 取得商店
      tags:
      - menu
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 新增商店
      parameters:
      - description: 商名
        in: formData
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 菜單
          schema:
            $ref: '#/definitions/resp.Shop'
            type: object
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 新增商店
      tags:
      - menu
  /menu/shop/{id}:
    delete:
      description: 刪除商店
      parameters:
      - description: 編號
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 刪除商店
      tags:
      - menu
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: 修改商店
      parameters:
      - description: 編號
        in: path
        name: id
        required: true
        type: integer
      - description: 店名
        in: formData
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 結果
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 修改商店
      tags:
      - menu
  /order:
    get:
      description: 取得訂單
      produces:
      - application/json
      responses:
        "200":
          description: 餐點
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 取得訂單
      tags:
      - order
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: 訂餐
      parameters:
      - description: 餐點
        in: formData
        name: orders
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 餐點
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 訂餐
      tags:
      - order
  /order/all:
    get:
      description: 取得所有訂單
      produces:
      - application/json
      responses:
        "200":
          description: 餐點
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 取得所有訂單
      tags:
      - order
  /shop:
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: 更改商店
      parameters:
      - description: 商店
        in: formData
        name: view
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 商店
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 更改商店
      tags:
      - manager
  /user:
    get:
      description: 取得用戶名稱
      produces:
      - application/json
      responses:
        "200":
          description: 用戶名稱
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 取得用戶名稱
      tags:
      - user
    put:
      consumes:
      - application/json
      description: 修改用戶名稱和密碼
      parameters:
      - description: 修改用戶資訊
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/reqs.ModifyUser'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: 用戶資訊
          schema:
            $ref: '#/definitions/models.Member'
            type: object
        "500":
          description: 内部错误
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 修改用戶資訊
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
